handle vars correctly for pit (#7727)

diff --git a/.github/workflows/pit.yml b/.github/workflows/pit.yml
--- a/.github/workflows/pit.yml
+++ b/.github/workflows/pit.yml
@@ -58,16 +58,17 @@ jobs:
     outputs:
       matrix: ${{ steps.set.outputs.matrix }}
     steps:
-      - id: set
+      - name: Compute Matrix
+        id: set
         shell: bash
         run: |
-          # COMPUTE MATRIX
-          echo "Computing matrix ..."
-          [ -z "${{secrets.GHTK}}" -o -z "${{secrets.TB_LICENSE}}" -o -z "${{secrets.SS_LICENSE}}" -o -z "${CE_LICENSE}" ] && exit 1
-          V="${{inputs.version}}"
-          [ -n "$V" ] && echo "$V" | grep -Eqv '^[0-9]+(\.[0-9]+)*(-SNAPSHOT|\.alpha[0-9]+|\.beta[0-9]+|\.rc[0-9]+)?$' && echo "Invalid version" && exit 1
+          [ -z "${{secrets.GHTK}}" ] && exit 1
+          curl -s -H "Authorization: Bearer ${{secrets.GHTK}}" https://api.github.com/repos/vaadin/platform | jq '.permissions'  | grep -q '"pull": true' || exit 1
 
-          git clone -q https://${{secrets.GHTK}}@github.com/vaadin/platform-in-test-script.git pit
+          V="${{inputs.version}}"
+          [ -n "$V" ] && echo "$V" | grep -Eqv '^[0-9]+(\.[0-9]+)*(-SNAPSHOT|\.alpha[0-9]+|\.beta[0-9]+|\.rc[0-9]+)?$' && echo "Invalid version" >&2 && exit 1
+
+          git clone -q https://github.com/vaadin/platform-in-test-script.git pit
           W="${{inputs.windows}}"
           L="${{inputs.linux}}"
           [ true != "$W" -a true != "$L" ] && W=true
@@ -88,8 +89,7 @@ jobs:
           M=`echo $M | sed -e s/,$//`']}'
           echo "Generated Matrix: $M"
           echo "matrix=$M" >> $GITHUB_OUTPUT
-        env:
-          CE_LICENSE: ${{secrets.CE_LICENSE}}
+          rm -rf pit
   run:
     needs: prepare
     strategy:
@@ -101,31 +101,28 @@ jobs:
         image: ${{ (matrix.app == 'control-center' ) && 'docker:dind' || '' }}
         options: --privileged --shm-size=2g
     steps:
-      - run: |
-          # TEST PARAMETERS
-          [ -z "${{matrix.app}}" ] && exit 1
-          echo "RUNNING TEST FOR ${{matrix.app}} APP"
+      - name: Check parameters
         shell: bash
-      - run: |
-          # INSTALL PIT
-          git clone https://${{secrets.GHTK}}@github.com/vaadin/platform-in-test-script.git pit
+        run: |
+          [ -n "${{matrix.app}}" ] && echo "RUNNING TEST FOR ${{matrix.app}} APP" || exit 1
+      - name: Setup ACT local runner
+        if: ${{ env.ACT }}
+        shell: bash
+        run: |
+          command -v sudo >/dev/null 2>&1 && S=sudo || S=
+          $S apt-get update -qq
+          $S apt-get install -qq -y vim iputils-ping curl git sudo unzip >/dev/null
+      - name: Install PiT
+        shell: bash
+        run: |
+          git clone -q https://github.com/vaadin/platform-in-test-script.git pit
           cd pit && git rev-parse --short HEAD
+      - name: Install Licenses
         shell: bash
-      - run: |
-          # INSTALL LICENSE
+        run: |
           mkdir -p ~/.vaadin/
           echo '{"username":"'`echo ${{secrets.TB_LICENSE}} | cut -d / -f1`'","proKey":"'`echo ${{secrets.TB_LICENSE}} | cut -d / -f2`'"}' > ~/.vaadin/proKey
           echo "${{secrets.SS_LICENSE}}" > ~/vaadin.spreadsheet.developer.license
-        shell: bash
-      - name: Setup ACT local runner
-        if: ${{ env.ACT }}
-        run: |
-          # LINUX LIBS (ACT)
-          # see https://github.com/browser-actions/setup-chrome/issues/240
-          sudo ./pit/scripts/pit/docker/setup.sh --lib-chrome
-      - uses: browser-actions/setup-chrome@latest
-        with:
-          chrome-version: stable
       - uses: actions/setup-node@v4
         with:
           node-version: '20'
@@ -145,33 +142,31 @@ jobs:
         if: ${{ matrix.app == 'control-center' }}
         uses: helm/kind-action@v1
         with:
-          install_only: false
-      - run: |
-          # PIT TESTS ${{matrix.app}} ${{inputs.version}}
+          cluster_name: pit
+      - name: Setup ACT vars
+        if: ${{ env.ACT }}
+        shell: bash
+        run: |
+          echo "PATH=$PATH" >> vars.sh
+      - name: Run PiT ${{matrix.app}} ${{inputs.version}}
+        shell: bash
+        run: |
           echo "${{toJSON(inputs)}}"
           [ -n "${{inputs.version}}" ] && ARG="--version=${{inputs.version}}"
           [ true = "${{inputs.skipcurrent}}" ] && ARG="$ARG --skip-current"
           [ true = "${{inputs.skipdev}}" ] && ARG="$ARG --skip-dev"
           [ true = "${{inputs.debug}}" ] && ARG="$ARG --debug"
-          ./pit/scripts/pit/run.sh --path
-          CMD="./pit/scripts/pit/run.sh $ARG --starters=${{matrix.app}}"
-          # Output the PiT command to execute, so as we can run the same locally
+          CMD="./pit/scripts/pit/run.sh $ARG --starters=${{matrix.app}} --ghtk=${{secrets.GHTK}}"
           echo "$CMD"
-          # Run PiT in test mode, so as we can copy and paste commands when reporting
-          $CMD --test
-          # Run PiT
           $CMD
         env:
-            GHTK: ${{secrets.GHTK}}
-            CE_LICENSE: ${{secrets.CE_LICENSE}}
-            OPENAI_TOKEN: ${{secrets.OPENAI_TOKEN}}
-            MAVEN_ARGS: ${{env.MAVEN_ARGS}}
-            CC_CERT: ${{secrets.CC_CERT}}
-            CC_KEY: ${{secrets.CC_KEY}}
-        shell: bash
-      - if: ${{ env.ACT }}
+          OPENAI_TOKEN: ${{secrets.OPENAI_TOKEN}}
+          MAVEN_ARGS: ${{env.MAVEN_ARGS}}
+          CC_CERT: ${{secrets.CC_CERT}}
+          CC_KEY: ${{secrets.CC_KEY}}
+      - name: ACT Wait
+        if: ${{ always() && env.ACT }}
         run: |
-          # WAIT (ACT)
           echo "Keeping docker container running, push Ctrl-C to terminate ..."
           read key
       - if: ${{failure()}}
